config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  root to: 'home#index'

  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get 'contact', to: 'static_pages#contact'
  # get 'team', to: 'static_pages#team'
  # get 'welcome/:user_entry', to: 'welcome#show'
  # resources :sessions, only: [:new, :create, :destroy]
  resources :users  
  resources :events
  resources :attendances



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord  
  belongs_to :attendee, class_name: "User", foreign_key: "stripe_customer_id"
  belongs_to :event

  after_create :attendance_created

  def attendance_created
    UserMailer.attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :guests, foreign_key: 'event_id', class_name: "User", through: :attendances


  validates :start_date,
    presence: true

  validate :start_date_is_in_future?

  validates :duration,
    presence: true,
    numericality: { greater_than_or_equal_to: 0 }
  
  validate :duration_is_a_multiple_of_5?

  validates :title,
    presence: true,
    length: { in: 5..140 }

  validates :description,
    presence: true,
    length: { in: 20..1000 }

  validates :price,
    presence: true,
    numericality: true,
    inclusion: { in: 1..1000, message: "Value should be between 1 and 1000"}

  validates :location,
    presence: true

  def start_date_is_in_future?
    errors.add(:start_date, "must be in the future") unless
       self.start_date > Time.now
  end

  def duration_is_a_multiple_of_5?
    errors.add(:duration, "must be a multiple of 5") unless
    self.duration % 5 == 0
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'guest_id', class_name: 'Attendance'

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end



  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
            </style>
        </head>

    <body>

    </body>


</html>

app/views/layouts/_navbar.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
<a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
  <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
</a>

<ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
  <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
  <li><a href="#" class="nav-link px-2 link-dark">Event</a></li>
</ul>

<div class="col-md-3 text-end">
  <button type="button" class="btn btn-outline-primary me-2"><%= link_to "Login", user_session_path %> </button>

  <button type="button" class="btn btn-primary"><%= link_to "Sign up", new_user_registration_path, :class => "text-light" %></button>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evenbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </head>

  <body style="display:flex;flex-direction:column">
  <%= render "layouts/navbar" %>
  <div class="container"> 
  <%= yield %>
  </div>

  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Eventbrite</h1>
<p>Bienvenu</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>